# -----------------------------
# ScholarSphere Eureka Server
# -----------------------------

spring.application.name=EUREKA-SERVER

server.port=8761

# Do not register Eureka server with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable self-preservation during development
eureka.server.enable-self-preservation=false

# Dashboard settings
eureka.instance.hostname=localhost